#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user" 2>&1
  exit 1
else
  echo "installing necessary files"
  apt update
  apt install net-tools python3 python3.8 -y
  chmod 777 macchanger-gui
  cp macchanger-gui /usr/bin/
  clear
  echo "all done"
  echo "type 'macchanger-gui' in terminal"
fi
